### ISSUE TITLE
possible missing property

### ISSUE THREAD

**Issue by SMT-Ryan** [mbelling/rpi-ws281x-java#2]
I copied the project down to my raspberry pi.

I installed swig on the pi and ran scripts/createNativeLib.sh without issue.

when I run ./gradlew assemble on my raspberry pi I get 

FAILURE: Build failed with an exception.

* Where:
Build file '/home/pi/Code/java/RPTest/lib/rpi-ws281x-java-master/build.gradle' line: 101

* What went wrong:
A problem occurred configuring root project 'rpi-ws281x-java'.
> Exception thrown while executing model rule: PublishingPlugin.Rules#publishing(ExtensionContainer)
   > Could not get unknown property 'sonatypeUsername' for Credentials [username: null] of type org.gradle.api.internal.artifacts.repositories.DefaultPasswordCredentials_Decorated.

I am having trouble tracking what I am missing to fill in this null.

thanks
Ryan

**Comment by SMT-Ryan** [comment]
forgive the amateurish question but I am not very familiar with gradle will I need gradle on my raspberry pi for it to install or are the scripts in the repo self-contained?

**Comment by mbelling** [comment]
The scripts in the repo are pretty self contained.  The `./gradlew` script will automatically download a gradle distribution to run the build.  All you should need on the Pi is a JDK so that the Java code can be compiled.

Related to the issue, I edited the gradle.properties on the site to add default values for those properties to hopefully fix the issue.  I am at work, so unable to test on the pi, but I think that should get you past the issue.

**Comment by SMT-Ryan** [comment]
when I run 

createNativeLib.sh

NeoPixel ws281x Library Compiler
****************************************************
Check - SWIG installed...
Check - GCC installed...
Check - AR installed...
Check - ranlib installed...
Check - git installed...
Deleting build directory to start clean...
Cloning rpi_ws281x repository...
Cloning into 'build/ws281x'...
remote: Counting objects: 709, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 709 (delta 8), reused 5 (delta 0), pack-reused 688
Receiving objects: 100% (709/709), 315.39 KiB | 396.00 KiB/s, done.
Resolving deltas: 100% (439/439), done.
Checking connectivity... done.
Checking out specific revision...
~/Code/java/rpi-ws281x-java-master/src/scripts/build/ws281x ~/Code/java/rpi-ws281x-java-master/src/scripts
Note: checking out '3a01777f51bebe412a23350f842fec7b43c00c5a'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 3a01777... Basic Golang Examples (#256)
~/Code/java/rpi-ws281x-java-master/src/scripts
Creating required dirs...
Building JNI interface using SWIG...
Unable to find file 'src/swig/rpi_ws281x.i'.
Compiling ws281x library objects...
Compiling ws281x library...
Creating archive...
Indexing archive...
Compiling wrapper into object...
gcc: error: build/swig/rpi_ws281x_wrap.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
Compiling wrapper into shared library...
gcc: error: build/swig/rpi_ws281x_wrap.o: No such file or directory
Cleaning up intermediate items...
Done!

**Comment by SMT-Ryan** [comment]
seems like maybe the create script didn't run completely for me the last time.

**Comment by mbelling** [comment]
From the log, it looks like you ran the script from within the src/scrpts directory.  The script in it's current form assumes you are running from the repository root. To get you up and running, try running that script from the base of the repo.

`src/scripts/createNativeLib.sh`

I'll create another PR to allow the script to be run from anywhere.

**Comment by SMT-Ryan** [comment]
okay 
/build/generatedSource/java/com/github/mbelling/ws281x 
exists and has content i think that confirms running from the repo's root worked.

**Comment by SMT-Ryan** [comment]
when I re-ran the gradle file I got to the seventh step out of seven before failing

 sudo ./gradlew assemble
:compileJava
:processResources
:classes
:jar
:javadoc
:javadocJar
:sourceJar
:signArchives FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signArchives'.
> Cannot perform signing task ':signArchives' because it has no configured signatory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
7 actionable tasks: 7 executed

**Comment by mbelling** [comment]
That is also related to the publishing changes in the build.  I might just remove those to alleviate these issues and find a way to add them only locally until I learn how to properly fix these types of issues.

**Comment by mbelling** [comment]
Commit 712d04a should hopefully fix that latest problem.

**Comment by SMT-Ryan** [comment]
yes I am able to build three jars after the latest PR

thank you
